// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Projeto.Infrastructure.Persistence;

#nullable disable

namespace Projeto.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(LojaVirtualContext))]
    partial class LojaVirtualContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Projeto.Domain.Entities.Categoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Descricao")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("Categorias", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("0b1d6c2e-5a1f-4c3a-9f10-000000000001"),
                            Descricao = "Periféricos e acessórios de informática",
                            Nome = "Eletrônicos"
                        },
                        new
                        {
                            Id = new Guid("0b1d6c2e-5a1f-4c3a-9f10-000000000002"),
                            Descricao = "Livros impressos e digitais",
                            Nome = "Livros e E-books"
                        });
                });

            modelBuilder.Entity("Projeto.Domain.Entities.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("char(11)")
                        .IsFixedLength();

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<Guid?>("EnderecoId")
                        .HasColumnType("char(36)");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Cpf")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("EnderecoId")
                        .IsUnique();

                    b.ToTable("Clientes", (string)null);
                });

            modelBuilder.Entity("Projeto.Domain.Entities.Endereco", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("char(8)")
                        .IsFixedLength();

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Complemento")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("char(2)")
                        .IsFixedLength();

                    b.HasKey("Id");

                    b.ToTable("Enderecos", (string)null);
                });

            modelBuilder.Entity("Projeto.Domain.Entities.ItemPedido", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("PedidoId")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("PrecoUnitario")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<Guid>("ProdutoId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoId");

                    b.HasIndex("PedidoId", "ProdutoId")
                        .IsUnique();

                    b.ToTable("ItensPedido", null, t =>
                        {
                            t.HasCheckConstraint("CK_ItensPedido_PrecoUnitario", "PrecoUnitario >= 0");

                            t.HasCheckConstraint("CK_ItensPedido_Quantidade", "Quantidade > 0");

                            t.HasCheckConstraint("CK_ItensPedido_Subtotal", "Subtotal >= 0");
                        });
                });

            modelBuilder.Entity("Projeto.Domain.Entities.Pedido", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("DataEntrega")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataPedido")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("Desconto")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("FormaPagamento")
                        .HasColumnType("int");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Observacao")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorTotal")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("Numero")
                        .IsUnique();

                    b.ToTable("Pedidos", null, t =>
                        {
                            t.HasCheckConstraint("CK_Pedidos_Desconto", "Desconto IS NULL OR Desconto >= 0");

                            t.HasCheckConstraint("CK_Pedidos_ValorTotal", "ValorTotal >= 0");
                        });
                });

            modelBuilder.Entity("Projeto.Domain.Entities.Produto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("char(36)");

                    b.Property<string>("CodigoBarras")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("varchar(13)");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("EstoqueAtual")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<decimal>("Preco")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("TipoProduto")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("CodigoBarras")
                        .IsUnique();

                    b.ToTable("Produtos", null, t =>
                        {
                            t.HasCheckConstraint("CK_Produtos_Digital", "TipoProduto <> 'Digital' OR (UrlDownload IS NOT NULL AND TamanhoArquivoMb IS NOT NULL)");

                            t.HasCheckConstraint("CK_Produtos_EstoqueAtual", "EstoqueAtual >= 0");

                            t.HasCheckConstraint("CK_Produtos_Fisico", "TipoProduto <> 'Fisico' OR (PesoGramas IS NOT NULL AND AlturaCm IS NOT NULL AND LarguraCm IS NOT NULL AND ComprimentoCm IS NOT NULL)");

                            t.HasCheckConstraint("CK_Produtos_Preco", "Preco >= 0");

                            t.HasCheckConstraint("CK_Produtos_TipoProduto", "TipoProduto IN ('Fisico', 'Digital')");
                        });

                    b.HasDiscriminator<string>("TipoProduto").HasValue("Produto");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Projeto.Domain.Entities.ProdutoDigital", b =>
                {
                    b.HasBaseType("Projeto.Domain.Entities.Produto");

                    b.Property<int?>("LimiteDownloads")
                        .HasColumnType("int");

                    b.Property<decimal>("TamanhoArquivoMb")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("UrlDownload")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("CK_Produtos_Digital", "TipoProduto <> 'Digital' OR (UrlDownload IS NOT NULL AND TamanhoArquivoMb IS NOT NULL)");

                            t.HasCheckConstraint("CK_Produtos_EstoqueAtual", "EstoqueAtual >= 0");

                            t.HasCheckConstraint("CK_Produtos_Fisico", "TipoProduto <> 'Fisico' OR (PesoGramas IS NOT NULL AND AlturaCm IS NOT NULL AND LarguraCm IS NOT NULL AND ComprimentoCm IS NOT NULL)");

                            t.HasCheckConstraint("CK_Produtos_Preco", "Preco >= 0");

                            t.HasCheckConstraint("CK_Produtos_TipoProduto", "TipoProduto IN ('Fisico', 'Digital')");
                        });

                    b.HasDiscriminator().HasValue("Digital");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5e7a9d4c-2b3f-4e8a-8c20-000000000002"),
                            Ativo = true,
                            CategoriaId = new Guid("0b1d6c2e-5a1f-4c3a-9f10-000000000002"),
                            CodigoBarras = "9786500000011",
                            Descricao = "E-book em PDF e EPUB",
                            EstoqueAtual = 0,
                            Nome = "E-book Clean Architecture na prática",
                            Preco = 39.90m,
                            LimiteDownloads = 3,
                            TamanhoArquivoMb = 12.50m,
                            UrlDownload = "https://loja.exemplo.com/downloads/ebook-clean-architecture"
                        });
                });

            modelBuilder.Entity("Projeto.Domain.Entities.ProdutoFisico", b =>
                {
                    b.HasBaseType("Projeto.Domain.Entities.Produto");

                    b.Property<int>("AlturaCm")
                        .HasColumnType("int");

                    b.Property<int>("ComprimentoCm")
                        .HasColumnType("int");

                    b.Property<int>("LarguraCm")
                        .HasColumnType("int");

                    b.Property<int>("PesoGramas")
                        .HasColumnType("int");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("CK_Produtos_Digital", "TipoProduto <> 'Digital' OR (UrlDownload IS NOT NULL AND TamanhoArquivoMb IS NOT NULL)");

                            t.HasCheckConstraint("CK_Produtos_EstoqueAtual", "EstoqueAtual >= 0");

                            t.HasCheckConstraint("CK_Produtos_Fisico", "TipoProduto <> 'Fisico' OR (PesoGramas IS NOT NULL AND AlturaCm IS NOT NULL AND LarguraCm IS NOT NULL AND ComprimentoCm IS NOT NULL)");

                            t.HasCheckConstraint("CK_Produtos_Preco", "Preco >= 0");

                            t.HasCheckConstraint("CK_Produtos_TipoProduto", "TipoProduto IN ('Fisico', 'Digital')");
                        });

                    b.HasDiscriminator().HasValue("Fisico");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5e7a9d4c-2b3f-4e8a-8c20-000000000001"),
                            Ativo = true,
                            CategoriaId = new Guid("0b1d6c2e-5a1f-4c3a-9f10-000000000001"),
                            CodigoBarras = "7891000000017",
                            Descricao = "Mouse óptico sem fio, 1600 DPI",
                            EstoqueAtual = 25,
                            Nome = "Mouse sem fio",
                            Preco = 89.90m,
                            AlturaCm = 4,
                            ComprimentoCm = 11,
                            LarguraCm = 7,
                            PesoGramas = 95
                        });
                });

            modelBuilder.Entity("Projeto.Domain.Entities.Cliente", b =>
                {
                    b.HasOne("Projeto.Domain.Entities.Endereco", "Endereco")
                        .WithOne("Cliente")
                        .HasForeignKey("Projeto.Domain.Entities.Cliente", "EnderecoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Endereco");
                });

            modelBuilder.Entity("Projeto.Domain.Entities.ItemPedido", b =>
                {
                    b.HasOne("Projeto.Domain.Entities.Pedido", "Pedido")
                        .WithMany("Itens")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Projeto.Domain.Entities.Produto", "Produto")
                        .WithMany("Itens")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("Projeto.Domain.Entities.Pedido", b =>
                {
                    b.HasOne("Projeto.Domain.Entities.Cliente", "Cliente")
                        .WithMany("Pedidos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Projeto.Domain.Entities.Produto", b =>
                {
                    b.HasOne("Projeto.Domain.Entities.Categoria", "Categoria")
                        .WithMany("Produtos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("Projeto.Domain.Entities.Categoria", b =>
                {
                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("Projeto.Domain.Entities.Cliente", b =>
                {
                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("Projeto.Domain.Entities.Endereco", b =>
                {
                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Projeto.Domain.Entities.Pedido", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("Projeto.Domain.Entities.Produto", b =>
                {
                    b.Navigation("Itens");
                });
#pragma warning restore 612, 618
        }
    }
}
